export { default as IconEdit } from "./IconEdit"
export { default as IconInfo } from "./IconInfo"
export { default as IconYoutube } from "./IconYoutube"
export { default as IconTwitter } from "./IconTwitter"
export { default as IconTelegram } from "./IconTelegram"
export { default as IconSave } from "./IconSave"
export { default as IconInstagram } from "./IconInstagram"
export { default as IconShare } from "./IconShare"
